version: "3"

services:
  app:
    container_name: todoapp
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - .:/app
    
  mongo:
    container_name: todoappmongodb
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - mynetwork
  
  networks:
    mynetwork:
      driver: bridge